### ISSUE TITLE
is there any API available by IPU ? btw great work!

### ISSUE THREAD

**Issue by divyanshj16** [Sid-2D/Outcome-IPU#1]

**Comment by Sid-2D** [comment]
No, I take the official PDFs and parse them myself.

**Comment by divyanshj16** [comment]
shall we create an API for other developers, so that they can use that in their projects? This way there will be distributed traffic on different apps and no app will crash because of load issues.

**Comment by Sid-2D** [comment]
I have already created an API and there are no load issues as of yet.
