### ISSUE TITLE
Aggregate Percentage is NaN in the downloaded report.

### ISSUE THREAD

**Issue by vibhor1997a** [Sid-2D/Outcome-IPU#5]

**Comment by Sid-2D** [comment]
Thank you for taking the time to raise an issue. Can you please share the roll number for which this occurs? As as it seems to work just fine for me.

**Comment by vibhor1997a** [comment]
`41311502715`. The issue is in the downloaded pdf.

**Comment by Sid-2D** [comment]
Ya, it doesn't seem to be there for the roll numbers I am testing on. Please share the roll number on which it is occurring.

**Comment by vibhor1997a** [comment]
41311502715 is the roll no!

**Comment by Sid-2D** [comment]
I have deployed a fix by only including the regular results while calculating the aggregates. Your name and a link to your Github has been added under the bug watchers section on the main page/README of this repo. Thanks for the help.
