### ISSUE TITLE
update result of 5th semester

### ISSUE THREAD

**Issue by deepak333gaur** [Sid-2D/Outcome-IPU#8]
update my result of software engineering in 5th semester. my roll no is 04720902714. update marks is 80. 20 in internal and 60 in external

**Comment by Sid-2D** [comment]
Thanks for bringing this to my attention. I will get on to fixing it.

**Comment by Sid-2D** [comment]
I just made the updates. Please take a look at your result again and notify me if everything looks alright or needs any further corrections. Currently we are making updates to reappear results on request basis only and will automate that process in the near future.

**Comment by deepak333gaur** [comment]
not its not updated. Total number of credit showing is showing 22 in
overall 5th semester but it must 26. The correct total number of credit for
5th sem is 26 not 22

**Comment by Sid-2D** [comment]
This issue has been closed because you have raised another issue with the same request. I am working on it...
